-- À coller dans Supabase > SQL Editor > Run
create table if not exists drivers (id serial primary key, prenom text not null, nom text not null, role text default 'chauffeur', telephone text, vehicule_id int);
create table if not exists vehicles (id serial primary key, modele text not null, type text, carburant text, consommation numeric, capacite_kg int, volume_m3 numeric, autonomie_km int, annee int, immat text, reservoir_l numeric);
create table if not exists tournees (id serial primary key, driver_id int references drivers(id), vehicle_id int references vehicles(id), date date default current_date, statut text default 'prevue');
create table if not exists livraisons (id text primary key, tournee_id int references tournees(id) on delete cascade, ordre int, client text, adresse text, lat double precision, lon double precision, statut text default 'a_faire');

alter table drivers enable row level security;
drop policy if exists read_drivers on drivers;
create policy read_drivers on drivers for select using (true);
alter table vehicles enable row level security;
drop policy if exists read_vehicles on vehicles;
create policy read_vehicles on vehicles for select using (true);
alter table tournees enable row level security;
drop policy if exists read_tournees on tournees;
create policy read_tournees on tournees for select using (true);
alter table livraisons enable row level security;
drop policy if exists read_livraisons on livraisons;
create policy read_livraisons on livraisons for select using (true);
insert into drivers (id,prenom,nom) values (1,'Jean','Dupont') on conflict (id) do nothing;
insert into drivers (id,prenom,nom) values (2,'Marie','Martin') on conflict (id) do nothing;
insert into drivers (id,prenom,nom) values (3,'Pierre','Bernard') on conflict (id) do nothing;
insert into drivers (id,prenom,nom) values (4,'Sophie','Durand') on conflict (id) do nothing;
insert into drivers (id,prenom,nom) values (5,'Thomas','Lefevre') on conflict (id) do nothing;
insert into drivers (id,prenom,nom,role) values (100,'Karim','Benali','chauffeur') on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (1,'Renault Master','Fourgon','Diesel',8.5,1500,12,800,2020) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (2,'Mercedes Sprinter','Camion benne','Diesel',10.2,3500,20,1000,2019) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (3,'Peugeot Boxer','Fourgon frigorifique','Diesel',9.8,1200,10,750,2021) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (4,'Volkswagen Crafter','Camion plateau','Diesel',11.0,4500,25,900,2020) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (5,'Fiat Ducato','Fourgon','Diesel',8.2,1400,11,850,2022) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (6,'Toyota Hilux','Pickup','Diesel',7.5,1000,2.5,900,2021) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (7,'Iveco Daily','Camion ridelle','Diesel',12.5,5000,30,700,2018) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,capacite_kg,volume_m3,autonomie_km,annee) values (8,'CitROEN Jumper','Fourgon longue','Diesel',9.3,1800,15,800,2020) on conflict (id) do nothing;
insert into vehicles (id,modele,type,carburant,consommation,immat,reservoir_l) values (100,'Renault Master 12 m³','Fourgon','gazole',9.5,'GH-482-KT',80) on conflict (id) do nothing;
insert into tournees (id,driver_id,vehicle_id) values (1,100,100) on conflict (id) do nothing;
insert into livraisons (id,tournee_id,ordre,client,adresse,lat,lon) values ('L1',1,1,'Boulangerie Martin','12 rue de Rivoli, Paris 4e',48.8556,2.36) on conflict (id) do nothing;
insert into livraisons (id,tournee_id,ordre,client,adresse,lat,lon) values ('L2',1,2,'Pharmacie Bastille','3 place de la Bastille, Paris 11e',48.8532,2.3692) on conflict (id) do nothing;
insert into livraisons (id,tournee_id,ordre,client,adresse,lat,lon) values ('L3',1,3,'Épicerie Oberkampf','98 rue Oberkampf, Paris 11e',48.8656,2.3779) on conflict (id) do nothing;
insert into livraisons (id,tournee_id,ordre,client,adresse,lat,lon) values ('L4',1,4,'Fleuriste Batignolles','40 rue des Batignolles, Paris 17e',48.8846,2.3196) on conflict (id) do nothing;
insert into livraisons (id,tournee_id,ordre,client,adresse,lat,lon) values ('L5',1,5,'Cave de Levallois','55 rue Rivay, Levallois',48.8925,2.2869) on conflict (id) do nothing;
select setval('drivers_id_seq',100); select setval('vehicles_id_seq',100); select setval('tournees_id_seq',1);
